### ISSUE TITLE
Erro: Ionic serve is not running on port 8100

### ISSUE THREAD

**Issue by RaphaelGNunes** [jadsonbr/ionic-preview#1]
Always show the error "Ionic serve is not running on port 8100"
Whats heppen?

**Comment by jadsonbr** [comment]
The ionic service must be running on port 8100 for correct operation.

Soon we will be launching a version for the configuration of the port of execution of the ionic serves

**Comment by RaphaelGNunes** [comment]
Is already configured on port 8100, and does not work

**Comment by jadsonbr** [comment]
You could give a browser print when you go to http://localhost:8100/

**Comment by RaphaelGNunes** [comment]
The browser with port 8100 and the error in visual studio code

![image](https://user-images.githubusercontent.com/11563814/28018320-3caa60f8-6553-11e7-9f28-55763cddd319.png)

**Comment by jadsonbr** [comment]
Is the ionic preview run after the ionic command serves?

**Comment by RaphaelGNunes** [comment]
I've tried it before and after, but it did not work. How would it be correct?

**Comment by jadsonbr** [comment]
Add my skype to understand your case better.

**jadson2026**

**Comment by RaphaelGNunes** [comment]
Você é brasileiro?

**Comment by jadsonbr** [comment]
Sim

**Comment by RaphaelGNunes** [comment]
Eu também, e a gente falando inglês.

**Comment by jadsonbr** [comment]
Adicionou no skype ?

**Comment by RaphaelGNunes** [comment]
adicionei agora

**Comment by jhitchcock** [comment]
I also have this issue

**Comment by jadsonbr** [comment]
We use the net module to check the connection.
To test if the module is working properly, run the command below and print the result so we can parse.

```javascript
const net = require('net');

var server = net.createServer(function(socket) {
    socket.write('Echo server\r\n');
    socket.pipe(socket);
});
server.listen(8100, '127.0.0.1');
    server.on('error', function (e) {
    console.log('>>>>>> Port in use <<<<<<');
});
server.on('listening', function (e) {
    server.close();
    console.log('>>>>>> Port is not in use. <<<<<<');
});
```

**Comment by carvarr** [comment]
I have this issue too

**Comment by rogeri10o** [comment]
Estou com o mesmo problema! Servidor previamente iniciado na porta 8100, mas o erro continua ocorrendo.

**Comment by jadsonbr** [comment]
We use the net module to check the connection.
To test if the module is working properly, run the command below and print the result so we can parse.

```javascript
const net = require('net');

var server = net.createServer(function(socket) {
    socket.write('Echo server\r\n');
    socket.pipe(socket);
});
server.listen(8100, '127.0.0.1');
    server.on('error', function (e) {
    console.log('>>>>>> Port in use <<<<<<');
});
server.on('listening', function (e) {
    server.close();
    console.log('>>>>>> Port is not in use. <<<<<<');
});
```

**Comment by rogeri10o** [comment]
só funcionou quando rodei subi o servidor assim: ionic serve --address 127.0.0.1
quando não passo o endereço o servidor usa o ip 0.0.0.0

**Comment by RaphaelGNunes** [comment]
Perfeito @rogeri10o agora sim funcionou.
Agora posso parabenizar o @jadsonbr pela extensão bem útil. Parabéns.

**Comment by jadsonbr** [comment]
We have put a configuration parameter for the host.
You can see the details in: [Docs Settings](https://github.com/jadsonbr/ionic-preview#settings)

Thanks @rogeri10o for the solution
