### ISSUE TITLE
Images are not displayed when working with Live Preview in VS Code

### ISSUE THREAD

**Issue by ayoubkhan558** [jadsonbr/ionic-preview#10]
Images are not displayed when working with Live Preview in VS Code

![github-ionic-preview-error](https://user-images.githubusercontent.com/20210961/56363213-1c42a900-6205-11e9-8834-8789c2b925b9.PNG)

Settings
![image](https://user-images.githubusercontent.com/20210961/56363282-485e2a00-6205-11e9-8a5c-f279463283b6.png)

**Comment by jadsonbr** [comment]
The plugin has a problem because the function "vscode.previewHtml" used by it has been deprecated.
We are working to release an update.

**Comment by jadsonbr** [comment]
@ayoubkhan558 

I launched version 0.0.20 that supports the new versions of vscode and corrects the problems mentioned.

[Marketplace](https://marketplace.visualstudio.com/items?itemName=ionic-preview.ionic-preview)

**Comment by ayoubkhan558** [comment]
Ok that's great. I will check/
