### ISSUE TITLE
Not working ionic preview

### ISSUE THREAD

**Issue by dinushchathurya** [jadsonbr/ionic-preview#15]
Ionic preview is not working for vs code. I have tried all the possible ways to do that but it's not working.

**Comment by nitorplus** [comment]
Same for me, tried on ionic 3 and 4 project with no error messages. 
Commands ran: 
```
ionic serve
ctrl+shift+P
Ionic Preview: Android
```

If i run it without ionic serve then i get the message: 

> We did not identify the Ionic serve running on host localhost on port 8100

**Comment by dinushchathurya** [comment]
> Same for me, tried on ionic 3 and 4 project with no error messages.
> Commands ran:
> 
> ```
> ionic serve
> ctrl+shift+P
> Ionic Preview: Android
> ```
> 
> If i run it without ionic serve then i get the message:
> 
> > We did not identify the Ionic serve running on host localhost on port 8100
> 
> I have also tried -
> 
> `ionic serve --address 127.0.0.1`
> 
> and changing the settings to localhost and viceversa.

I think the issue is with the Visual Studio Code's latest update.

**Comment by jadsonbr** [comment]
The plugin has a problem because the function "vscode.previewHtml" used by it has been deprecated.
We are working to release an update.

**Comment by jadsonbr** [comment]
@dinushchathurya 

I launched version 0.0.20 that supports the new versions of vscode and corrects the problems mentioned.

[Marketplace](https://marketplace.visualstudio.com/items?itemName=ionic-preview.ionic-preview)

**Comment by dinushchathurya** [comment]
Good job @jadsonbr & Thank you. 😍

**Comment by bluesvisions** [comment]
I just downloaded version 0.0.20 on 5/17 and the screen of the mobile device appears but the screen is blank. The code consists of HTML and some CSS.

**Comment by jadsonbr** [comment]
Is the ionic server running?

**Comment by bluesvisions** [comment]
Is that an extension I need to download? 


-------- Original Message --------
Subject: Re: [jadsonbr/ionic-preview] Not working ionic preview (#15)

**Comment by jadsonbr** [comment]
@bluesvisions 
Ionic offers a library of mobile-optimized UI components, gestures, and tools for building fast, highly interactive apps.

See more at the link below.
[ionic framework](https://ionicframework.com)

Nothing prevents you from running another responsive application served and want to display it using this plugin as long as the host and port are properly configured.

[Settings](https://github.com/jadsonbr/ionic-preview#settings)

**Comment by jadsonbr** [comment]
@dinushchathurya 

If resolved, please close the issue.

**Comment by bluesvisions** [comment]
It is not really resolved since my problem still exists. I am unable to use the extension. 


-------- Original Message --------
Subject: Re: [jadsonbr/ionic-preview] Not working ionic preview (#15)

**Comment by jadsonbr** [comment]
Nothing prevents you from running another responsive application served and want to display it using this plugin as long as the host and port are properly configured.
[Settings](https://github.com/jadsonbr/ionic-preview#settings)

Exemples:
A responsive web **python** application
```
python -m SimpleHTTPServer 8100
```

A responsive web **php** application
```
php -s localhost:8100
```

Dart web
```
webdev serve web test:8100
```

Or any other application that is served on the web and is responsive.

[Framework7](https://framework7.io)
[OnSen](https://onsen.io)
[Quasar Framework](https://quasar.dev)
[JQueryMobile](https://jquerymobile.com)
...
