### ISSUE TITLE
No source code?

### ISSUE THREAD

**Issue by auchenberg** [jadsonbr/ionic-preview#2]
Is this an OSS project or is this repo only for issue tracking?

**Comment by jadsonbr** [comment]
Issue tracking and documentation.
To use install [https://marketplace.visualstudio.com/items?itemName=ionic-preview.ionic-preview](https://marketplace.visualstudio.com/items?itemName=ionic-preview.ionic-preview)

**Comment by jadsonbr** [comment]
Source code added
