### ISSUE TITLE
Problema ao iniciar o plugin

### ISSUE THREAD

**Issue by viniciosyals** [jadsonbr/ionic-preview#3]
Ao iniciar o plugin aparece a seguinte mensagem de erro.

``We did not identify the Ionic serve running on host 127.0.0.1 on port 8100``

O projeto está rodando normalmente pelo browser no mesmo host e na mesma porta.

**Comment by jadsonbr** [comment]
For your problem see in:
  https://github.com/jadsonbr/ionic-preview#settings

Try to set the host 0.0.0.0
Or run ionic serve --adress 127.0.0.1

**Comment by viniciosyals** [comment]
"ionic-preview.host": "0.0.0.0"

Works, thanks! =)
