### ISSUE TITLE
We did not identify the Ionic serve running on host 127.0.0.1 on port 8100

### ISSUE THREAD

**Issue by Muhammad7Salah** [jadsonbr/ionic-preview#4]
The app is working on browser but it provide this error when I use the extension
I tried to manually use the host and port in the error and it worked correctly on my browser!

**Comment by jadsonbr** [comment]
Try to set the host 0.0.0.0
Or run ionic serve --adress 127.0.0.1

[Docs](https://github.com/jadsonbr/ionic-preview#settings)

**Comment by sephferiuz** [comment]
how to set host 0.0.0.0?

typing ionic serve --adress 127.0.0.1 opens as if it were "ionic serve

**Comment by jadsonbr** [comment]
@sephferiuz 
You can parameterize the host and port that the ionic-preview will check.
See more in the link below

[Documentation link](https://github.com/jadsonbr/ionic-preview#settings)

**Comment by sephferiuz** [comment]
Yes! I already have everything configured, but when I click on "ionic preview: android" I get a message "We did not identify the Ionic serve running on host 127.0.0.1 on port 8100".
with this extension is it possible for me to visualize the "ionic serve" within the vscode?

I do not know what could be wrong.

**Comment by jadsonbr** [comment]
The ionic serve should be running on a terminal before you attempt to run the ionic-preview.

Ionic-preview does not rotate the ionic serve

**Comment by sephferiuz** [comment]
I enter the directory by CMD, give ionic serve, then open vscode by CMD "code". and then clicking android ionic preview continues with the message. I do not know what it can be, but I'll let it go without a moment, then I'll try harder. I must be forgetting something that's all for certain. Thanks for answering me!

**Comment by sazekee** [comment]
ionic serve --address 127.0.0.1

RESOLVED

**Comment by LiamKarlMitchell** [comment]
Can this instead just work with default ionic serve?
it binds to 0.0.0.0

Appears to fix put this in your user settings.

"ionic-preview.host": "localhost"
